### ISSUE TITLE
[suggestion]: rename "active-settings" to "settings-mobile" (or maybe only "settings" when thinking about future conversion)?

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm#176]

**Comment by sebasje** [comment]
I've renamed the binary to plasma-settings. It's already reflected in the package, and transparant to the user.

**Comment by bhush9** [comment]
I got reports of not being able to start plasma-settings in IMG138

Turns out in desktop files above change was not reflected. I've made quick fix at http://commits.kde.org/plasma-settings/ef0970599abd0a229a7ee2ed1ee31ec002a5966d

Which needs packaging..

**Comment by bhush9** [comment]
Fixed in plasma-settings (0.0.1ubuntu4+git20150812.1209+15.04-0)
