### ISSUE TITLE
Launchers: clean up 3 x "okular/document viewer"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm#179]

**Comment by bhush9** [comment]
Till issue #168 is not solved : I did blacklist them in http://commits.kde.org/plasma-phone-settings/8bdced09f74c9daac23cc9c1389c2adf9686ae34

**Comment by bhush9** [comment]
Wordview microsoft also gone : http://commits.kde.org/plasma-phone-settings/9b588aa0b3cc0b0f6f79753fd3b9a2c0252e5df0

**Comment by jriddell** [comment]
looks built

**Comment by star-buck** [comment]
Please remember not to close issues until confirmed to work on an actual IMG+1 in the future.

**Comment by star-buck** [comment]
now all three are gone, it should have left 1x icon document viewer (the mobile version).

**Comment by bhush9** [comment]
okular-mobile package needs to be installed by default on IMG.
