### ISSUE TITLE
[Qt] integrate patches for inline edit menus

### ISSUE THREAD

**Issue by notmart** [blue-systems/pm#189]
Qt (qtquickcontrols) needs the two following (already upstreamed, but only in dev, so 5.6) patches:
https://codereview.qt-project.org/#/c/121709/
https://codereview.qt-project.org/#/c/121659/

this will make the plasma feature in
https://git.reviewboard.kde.org/r/124374/
actually work

**Comment by notmart** [comment]
another patch needed:
https://codereview.qt-project.org/#/c/125032/

**Comment by jriddell** [comment]
https://codereview.qt-project.org/#/c/121709/ doesn't apply to the version of Qt we're using, 5.4.1.  Could you remake it for this version?

**Comment by notmart** [comment]
this is the patch redone on 5.4
https://paste.kde.org/p8tmyfrbn

**Comment by jriddell** [comment]
Uploaded qtquickcontrols-opensource-src_5.4.1-0ubuntu1plasma1 to mobile kci with your 2 patches
