### ISSUE TITLE
Test Plasma Mobile SDK on neon-mobile ISO installed system (desktop or laptop)

### ISSUE THREAD

**Issue by aleixpol** [blue-systems/pm#190]
Here's a test script
http://quickgit.kde.org/?p=xbuilder.git&a=blob&f=test%2Fdocker-test.rb&o=plain

I'm unsure how to proceed.

**Comment by aleixpol** [comment]
Ping?

**Comment by notmart** [comment]
testing it (had to change /bin/ruby to /usr/bin/ruby and had to run the script as root)

what i should look for?

**Comment by bhush9** [comment]
"had to run the script as root"

You have to add your user to ```docker``` group

**Comment by bhush9** [comment]
I am confused.. you want this on plasma mobile ISO? or want to CI'fy this at mobile.kci.pangea.pub:8080 ??

**Comment by star-buck** [comment]
imo start testing the SDK by installing it under a running mobile KCI ISO.
so not install it default on the ISO.

**Comment by aleixpol** [comment]
Well, the plan is to have it running on the servers, so that we can get a good-old red light when it stops working. It can stop working mostly for packaging issues (i.e. multiarch) so I'd say it makes sense for it to stay in mobile.kci.pangea.pub:8080 and it was implemented as Harald suggested to that end, providing a script that would be supposedly trivial to integrate in that jenkins instance.

**Comment by jriddell** [comment]
Add to jenkins, sorry for the delay
http://mobile.kci.pangea.pub:8080/job/xbuilder

**Comment by aleixpol** [comment]
Looks good, thanks a lot!!

**Comment by bhush9** [comment]
mmm.. this script needs to be changed in a way so that it doesn't pickup cached image and just move on..

http://mobile.kci.pangea.pub:8080/job/xbuilder/

this script is not actually building image and installing packages but just picking things from cache and moves on..
