### ISSUE TITLE
Launchers: blacklist "wordview microsoft"

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm#193]

**Comment by bhush9** [comment]
http://commits.kde.org/plasma-phone-settings/9b588aa0b3cc0b0f6f79753fd3b9a2c0252e5df0

**Comment by jriddell** [comment]
looks like the new package is built

**Comment by star-buck** [comment]
reopen - not closing until confirmed fixed on an actual IMG.

**Comment by star-buck** [comment]
that one is gone
