### ISSUE TITLE
[IMG v4]: flickering, no malitt, no document viewer at all (among other things...)

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm#196]
is it just me bad flashing or this latest version (4) seems flickering, when starting konsole one cannot activate malitt, no document viewer at all?

**Comment by bhush9** [comment]
Flickering is currently known issue, yes.. something is broken in libhybris or kwin side.

**Comment by star-buck** [comment]
okay, closing this then as its not me flashing a bad version... will seperate each finding into its own ticket.
