### ISSUE TITLE
[homescreen]: bottom-panel flickers

### ISSUE THREAD

**Issue by star-buck** [blue-systems/pm#200]

**Comment by mgraesslin** [comment]
The reason for this problem was that we now support blur and contrast effect. And those seem to not like gles hardware. Disabled for the moment: http://commits.kde.org/plasma-phone-settings/2bb8139803fe78bd6838f05e47c9ba4d0c289b83

**Comment by bhush9** [comment]
In IMG9 20151010.081111

**Comment by star-buck** [comment]
works, flickr gone
