### ISSUE TITLE
Fix xbuilder test script

### ISSUE THREAD

**Issue by aleixpol** [blue-systems/pm#208]
As @bhush9 reported:
>mmm.. this script needs to be changed in a way so that it doesn't pickup cached image and just move on..
>http://mobile.kci.pangea.pub:8080/job/xbuilder/
>this script is not actually building image and installing packages but just picking things from cache and moves on..

**Comment by aleixpol** [comment]
Passed --no-cache=true, should be fixed.

**Comment by bhush9** [comment]
Works now properly.
